### ISSUE TITLE
Change @themesberg/flowbite to flowbite

### ISSUE THREAD

**Issue by zoltanszogyenyi** [shinokada/svelte-flow#1]
Hey @shinokada,

Awesome repository!

Please change `@themesberg/flowbite` to `flowbite` in `package.json` and all the imports.

We've recently renamed the project and decided that it is easier to do it sooner, rather than later.

Thanks!

**Comment by shinokada** [comment]
@zoltanszogyenyi Thank. I just updated. And thank you for your awesome work. Please keep updated if you make any major changes.
