### ISSUE TITLE
Tailwind CSS class names should not be constructed dynamically

### ISSUE THREAD

**Issue by pierredewilde** [shinokada/svelte-flow#5]
Svelte Flow component class names are constructed dynamically:

```
bg-{color}-100 
bg-{btnColor}-700
text-{textColor}-400
text-{size} 
...
```

Unfortunately, it prevents Tailwind CSS to detect class names correctly.
https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

Don't construct class names dynamically
`<div class="text-{{ error ? 'red' : 'green' }}-600"></div>`

Always use complete class names
`<div class="{{ error ? 'text-red-600' : 'text-green-600' }}"></div>`

**Comment by pierredewilde** [comment]
Flowbite CSS has only partial list of Tailwind CSS colors:

![Screenshot 2022-02-17 at 00 08 49](https://user-images.githubusercontent.com/762445/154376945-b6994bdb-6947-4d78-ab53-a81581a0d2c7.png)

You may drop Flowbite CSS from `__layout.svelte`:
```
<script>
  import "../app.css"
  // import "flowbite/dist/flowbite.min.css"
</script>

```
and configure Tailwind CSS to scan Svelte Flow components:
```
const config = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/svelte-flow/**/*.{html,js,svelte,ts}",
  ]
}
module.exports = config;
```

Since component class names are constructed dynamically, you loose most of colors:

![Screenshot 2022-02-17 at 00 11 38](https://user-images.githubusercontent.com/762445/154377224-7743f33d-47c5-47e1-9366-5d0f262349de.png)

**Comment by pierredewilde** [comment]
A possible workaround is to configure Tailwind CSS to include all colors:

```
const prefixes = "border|bg|text|shadow|ring";
const bw = "black|white";
// const grays = "slate|gray|zinc|neutral|stone";
const grays = "gray";
const reds = "pink|rose|red|orange";
const yellows = "amber|yellow";
const greens = "lime|green|emerald|teal";
const blues = "cyan|sky|blue|indigo";
const violets = "violet|purple|fuchsia";
const colors = `${bw}|${grays}|${reds}|${yellows}|${greens}|${blues}|${violets}`;
const config = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/svelte-flow/**/*.{html,js,svelte,ts}",
  ],
  safelist: [
    { pattern: new RegExp(`(${prefixes})-(${colors})`) }
  ],
}
module.exports = config;
```

You may easily customize this list to reduce generated .css file.

![Screenshot 2022-02-17 at 00 12 39](https://user-images.githubusercontent.com/762445/154377322-b3b16977-399a-48c4-b05c-ebab26a09f96.png)

**Comment by pierredewilde** [comment]
Here is the content of `index.svelte` used to test all colors:
```
<script>
  import { Alert } from "svelte-flow";
</script>

<br>
<Alert alertId="alert-gray" color="gray" closeBtn="true">A simple gray alert with a close button.</Alert>
<br>
<Alert alertId="alert-pink" color="pink" closeBtn="true">A simple pink alert with a close button.</Alert>
<Alert alertId="alert-rose" color="rose" closeBtn="true">A simple rose alert with a close button.</Alert>
<Alert alertId="alert-red" color="red" closeBtn="true">A simple red alert with a close button.</Alert>
<Alert alertId="alert-orange" color="orange" closeBtn="true">A simple orange alert with a close button.</Alert>
<br>
<Alert alertId="alert-amber" color="amber" closeBtn="true">A simple amber alert with a close button.</Alert>
<Alert alertId="alert-yellow" color="yellow" closeBtn="true">A simple yellow alert with a close button.</Alert>
<br>
<Alert alertId="alert-lime" color="lime" closeBtn="true">A simple lime alert with a close button.</Alert>
<Alert alertId="alert-green" color="green" closeBtn="true">A simple green alert with a close button.</Alert>
<Alert alertId="alert-emerald" color="emerald" closeBtn="true">A simple emerald alert with a close button.</Alert>
<Alert alertId="alert-teal" color="teal" closeBtn="true">A simple teal alert with a close button.</Alert>
<br>
<Alert alertId="alert-cyan" color="cyan" closeBtn="true">A simple cyan alert with a close button.</Alert>
<Alert alertId="alert-sky" color="sky" closeBtn="true">A simple sky alert with a close button.</Alert>
<Alert alertId="alert-blue" color="blue" closeBtn="true">A simple blue alert with a close button.</Alert>
<Alert alertId="alert-indigo" color="indigo" closeBtn="true">A simple indigo alert with a close button.</Alert>
<br>
<Alert alertId="alert-violet" color="violet" closeBtn="true">A simple violet alert with a close button.</Alert>
<Alert alertId="alert-purple" color="purple" closeBtn="true">A simple purple alert with a close button.</Alert>
<Alert alertId="alert-fuchsia" color="fuchsia" closeBtn="true">A simple fuchsia alert with a close button.</Alert>
```

**Comment by shinokada** [comment]
Thank you for your contribution.

I will implement it your suggestions and update the demo site. 
If you notice something more, please let me know.

Thanks again.

**Comment by shinokada** [comment]
I use the following to wrap a demo:

```
<div class="rounded-xl w-full my-4 mx-auto bg-gradient-to-r bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 p-2 sm:p-6">
<Alert alertId="alert-fuchsia" color="fuchsia" closeBtn="true">A simple fuchsia alert with a close button.</Alert>
...
</div>
```

But it doesn't work.

Before:

![image](https://user-images.githubusercontent.com/147320/154390343-54adecf7-5e46-4a0b-a5b1-a244fc28beaa.png)

After: 
![image](https://user-images.githubusercontent.com/147320/154390393-16f1eeae-5215-4d85-b2d2-48120269f72c.png)

Do you have any idea why this happens and how to fix this?

**Comment by shinokada** [comment]
I need to keep the flowbite.css.

```
<script>
  import "../app.css"
  import "flowbite/dist/flowbite.min.css"
</script>
```

Then it works.

![image](https://user-images.githubusercontent.com/147320/154392016-818aef6e-04ae-4329-8747-196f6421d281.png)

**Comment by shinokada** [comment]
@pierredewilde How can I add `hover:bg` to `const prefixes`?

I tried this but seems not working:

```
const prefixes = "border|bg|text|shadow|ring|hover:bg";
```

**Comment by shinokada** [comment]
I added variants and hover is working.

```
safelist: [
    {
      pattern: new RegExp(`(${prefixes})-(${colors})`),
      variants: ['lg', 'hover', 'focus', 'lg:hover'],
    },
```

**Comment by shinokada** [comment]
`bg-gradient-to-r` is not working. I'm not sure how to fix this.

**Comment by shinokada** [comment]
`rounded-xl` is not working.

**Comment by pierredewilde** [comment]
Thank you for your investigation.

`rounded-xl` and `my-4` are correctly applied:

![Screenshot 2022-02-17 at 10 54 46](https://user-images.githubusercontent.com/762445/154457798-5dd513b1-f56d-4c6e-a322-03b98e301efd.png)

You probably need to stop/restart your dev server after tailwind.config.cjs modifications.

`bg-gradient-to-r` is also applied but you need to specify `from-` and `to-` colors to view it:

```
<div class="rounded-xl w-full my-4 mx-auto bg-gradient-to-r from-white to-black dark:from-black dark:to-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 p-2 sm:p-6">
```
![Screenshot 2022-02-17 at 11 04 57](https://user-images.githubusercontent.com/762445/154457889-165fc53a-8c44-49fd-9170-fe36737d0ee3.png)

![Screenshot 2022-02-17 at 11 05 29](https://user-images.githubusercontent.com/762445/154457948-3822d4b4-9804-43a3-b21a-557d873ee4db.png)

You are right about color variants. It must be added into tailwind.config.cjs:
```
  safelist: [
    { 
      pattern: new RegExp(`(${prefixes})-(${colors})`),
      variants: ['dark','focus','hover','dark:hover']
    },
  ],
```

The problem with this workaround is that it generates a huge .css file.

This is a **Tailwind CSS design issue** because each variant requires separated classes.
Although OK for static pages, it becomes problematic for dynamic components as Svelte Flow.

To get an estimation of the generated .css file with color variants:

- each color type requires ~1Kb
- 5 color types (border|bg|text|shadow|ring)
- 18 colors (+ black/white)
- 1 normal + 4 variants ['dark','focus','hover','dark:hover']

The previous config will generate ~450kb only for the colors excluding normal CSS.

Remember the Tailwind CSS design principle:

**_Always use complete class names. Don't construct class names dynamically._**

A `switch/case` (or `if/else if`) with supported colors and complete class names is probably the best approach.

You have already done it in `Button.svelte`. 
Please note that `text-${size}` should be renamed into `${text-size}` to respect the design principle.

HTH,
Pierre

**Comment by shinokada** [comment]
Thank you for your suggestions. I will go for a smaller file size without increasing colors for now.
But I will change variables to complete class names as you suggested.
Thanks again.

**Comment by shinokada** [comment]
@pierredewilde 
I'm updating BorderAlert.svetle. I can't get `border-pink-500`, `border-indigo-500`,  and `border-purple-500`.
Do you have any idea?

**Comment by pierredewilde** [comment]
BTW, if you still use dynamic class names like `border-{color}-500` in your components, you can _trick_ Tailwind CSS with comments containing class names:
```
<!-- include Tailwind CSS colors: border-pink-500 border-indigo-500 border-purple-500 -->
```

**Comment by shinokada** [comment]
@pierredewilde 
Thank you. In order to keep file size small. I still `import "flowbite/dist/flowbite.min.css"` in __layout.svelte.
I changed from `text-{size}` to `{textSize}`, and changed all the dynamic naming `bg-{color}-700` etc. to complete naming as you suggested.

Also I added:

```
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/svelte-flow/**/*.{html,js,svelte,ts}",
  ],
```
to scan source files.
Thanks again.

**Comment by pierredewilde** [comment]
You're welcome. Thank you for creating Svelte-Flow.
